mcp_proxy:
  endpoint_url: "http://127.0.0.1:7111"
  timeout: 300.0

orchestrator:
  type: thinkingbox
  agent_model:
    type: aoai_responses
    deployment: "<YOUR_DEPLOYMENT>"
    endpoint_url: "<YOUR_APIM_ENDPOINT>/v1/responses"
    client_certificate: "/path/to/your/client.pem" # TODO: Path to your PEM certificate file with concatenated client key and certificate
    is_reasoning: true
    reasoning_effort: medium
    reasoning_source: none
    temperature: 1.0
    max_completion_tokens: 4096
    timeout: 600.0

judge_model:
  # AOAI Chat Completions
  type: aoai
  endpoint_url: "<YOUR_APIM_ENDPOINT>/v1/chat/completions"
  client_certificate: "/path/to/your/client.pem" # TODO: Path to your PEM certificate file with concatenated client key and certificate
  deployment: "<YOUR_JUDGE_DEPLOYMENT>"
  temperature: 0.0
  seed: 42
  max_completion_tokens: 128
  timeout: 600.0

judge_type: "legacy" # or "motivation"

user_model:
  # AOAI Chat Completions
  type: aoai
  endpoint_url: "<YOUR_APIM_ENDPOINT>/v1/chat/completions"
  client_certificate: "/path/to/your/client.pem" # TODO: Path to your PEM certificate file with concatenated client key and certificate
  deployment: "<YOUR_USER_DEPLOYMENT>"
  temperature: 0.0
  max_completion_tokens: 4096
  timeout: 600.0
